# Generated by Django 4.2.7 on 2024-02-17 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feedback",
            new_name="feed",
        ),
        migrations.AddField(
            model_name="feedback",
            name="date_marked",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.TextField(max_length=105, unique=True),
        ),
    ]
