# Generated by Django 5.0.1 on 2024-02-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
        ("feedback", "0003_event_event_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="csp_log.deptprofile",
                to_field="dept_id",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="event_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.event",
                to_field="event_name",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="csp_log.userprofile",
                to_field="id_number",
            ),
        ),
    ]
