# Generated by Django 5.0.1 on 2024-02-26 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
        ("feedback", "0004_alter_event_dept_id_alter_feedback_event_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="csp_log.deptprofile"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="event_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedback.event"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="csp_log.userprofile"
            ),
        ),
    ]
