# Generated by Django 5.0.1 on 2024-02-26 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0003_alter_deptprofile_name"),
        ("feedback", "0006_alter_event_dept_id_alter_feedback_event_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="dept_id",
        ),
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="csp_log.deptprofile",
                to_field="name",
            ),
            preserve_default=False,
        ),
    ]
