# Generated by Django 5.0.1 on 2024-03-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0007_remove_event_dept_id_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
