# Generated by Django 5.0.1 on 2024-03-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0004_userprofile_gender"),
        ("feedback", "0008_alter_feedback_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="report_bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csp_log.userprofile",
                        to_field="id_number",
                    ),
                ),
            ],
        ),
    ]
