# Generated by Django 5.0.1 on 2024-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gov_pdf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="pdf_previews/"),
        ),
    ]
