# Generated by Django 5.0.1 on 2024-03-09 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gov_pdf", "0006_alter_pdfdocument_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfdocument",
            name="preview_image",
        ),
    ]
