# Generated by Django 5.0.1 on 2024-03-22 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0004_userprofile_gender"),
        ("gov_pdf", "0007_remove_pdfdocument_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="name",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="csp_log.deptprofile",
                to_field="name",
            ),
            preserve_default=False,
        ),
    ]
