# Generated by Django 5.0.1 on 2024-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deptprofile",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
