# Generated by Django 5.0.1 on 2024-03-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0003_alter_deptprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
