# Generated by Django 4.2.7 on 2024-02-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.CharField()),
                ("prob", models.TextField()),
                ("loc", models.TextField()),
                ("image", models.ImageField(upload_to="admin_images/")),
                ("is_read", models.BooleanField(default=False)),
                (
                    "id_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csp_log.userprofile",
                    ),
                ),
            ],
        ),
    ]
