# Generated by Django 4.2.7 on 2024-02-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
        ("complaint", "0002_alter_complaint_is_read_alter_complaint_sub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="id_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="csp_log.userprofile",
                to_field="id_number",
            ),
        ),
    ]
