# Generated by Django 5.0.1 on 2024-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complaint", "0006_alter_complaint_loc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
