# Generated by Django 5.0.1 on 2024-02-26 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("complaint", "0007_alter_complaint_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="is_read",
        ),
    ]
