# Generated by Django 4.2.7 on 2024-02-18 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey_A",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(max_length=255)),
                ("time_sub", models.DateTimeField(auto_now_add=True)),
                (
                    "id_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csp_log.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Survey_Q",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=255, unique=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csp_log.deptprofile",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="survey",
        ),
        migrations.RemoveField(
            model_name="response",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="response",
            name="survey",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="dept_id",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Response",
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
        migrations.AddField(
            model_name="survey_a",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.survey_q"
            ),
        ),
    ]
