# Generated by Django 5.0.1 on 2024-02-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
        ("survey", "0002_survey_a_survey_q_remove_choice_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey_a",
            name="id_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="csp_log.userprofile",
                to_field="id_number",
            ),
        ),
        migrations.AlterField(
            model_name="survey_a",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.survey_q",
                to_field="question",
            ),
        ),
        migrations.AlterField(
            model_name="survey_q",
            name="dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="csp_log.deptprofile",
                to_field="dept_id",
            ),
        ),
    ]
