# Generated by Django 5.0.1 on 2024-02-26 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csp_log", "0002_citizenlogin_deptlogin_and_more"),
        ("survey", "0003_alter_survey_a_id_number_alter_survey_a_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey_a",
            name="id_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="csp_log.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="survey_a",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.survey_q"
            ),
        ),
        migrations.AlterField(
            model_name="survey_q",
            name="dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="csp_log.deptprofile"
            ),
        ),
    ]
