# Generated by Django 5.0.1 on 2024-03-04 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0006_remove_survey_q_dept_id_survey_q_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey_q",
            name="is_options",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="survey_q",
            name="options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
